networks:
  chiwi_network:
    driver: bridge
    name: chiwi_network  # Nombre explícito
    attachable: true     # Permite conectar contenedores manualmente

volumes:
  db_users_server_data:
    driver: local
  mongodb_data:  # Nuevo volumen para MongoDB
    driver: local

services:
  db_users:
    image: mysql:8.0
    container_name: db_users
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Chiwineitor
      MYSQL_DATABASE: users_db
    volumes:
      - db_users_server_data:/var/lib/mysql
    networks:
      chiwi_network:
        aliases:
          - db_users
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$Chiwineitor --silent"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 30s

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ChiwireadorMongo  # Cambia esto por tu contraseña
    volumes:
      - mongodb_data:/data/db
    networks:
      chiwi_network:
        aliases:
          - mongodb
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  usuarios_service:
    image: gusher/chiwichat:usuarios-latest  # Usando la imagen de Docker Hub
    container_name: usuarios-service
    restart: unless-stopped
    volumes:
      - ./usuarios_service:/var/www/html
    environment:
      - DB_HOST=db_users
      - DB_USER=root
      - DB_PASSWORD=Chiwineitor
      - DB_DATABASE=users_db
      - DB_USERS_PORT=3306  
      - JWT_SECRET=DiosMioLaUPTAEBEstaAcabandoConmigo
      - APP_ENV=production
      - APP_DEBUG=false
      - URL_CRYPTO=http://chiwicrypt:80/
    networks:
      chiwi_network:
        aliases:
          - usuarios_service
    depends_on:
      - db_users
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: apache2-foreground

  chats_service_mongo:
    image: gusher/chiwichat:chats-latest    # Usando la imagen de Docker Hub
    container_name: chats-service-mongo
    restart: always
    volumes:
      - ./chats_service_mongo:/var/www/html  # Crea esta carpeta
    environment:
      - DB_TYPE=mongodb  # Nueva variable para identificar el tipo de DB
      - MONGO_HOST=mongodb
      - MONGO_USER=root
      - MONGO_PASSWORD=ChiwireadorMongo
      - MONGO_DATABASE=chats_mongo
      - APP_ENV=production
      - APP_DEBUG=false
      - URL_CRYPTO=http://chiwicrypt:80/
    networks:
      chiwi_network:
        aliases:
          - chats_service_mongo
    depends_on:
      - mongodb

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: apache2-foreground

  chiwicrypt:
    image: gusher/chiwichat:encrypt-latest  # Usando la imagen de Docker Hub
    restart: always
    networks:
      - chiwi_network
    volumes:
      # Los volúmenes deben estar bajo cada servicio
      - ./ChiwiCrypt:/var/www/html
    environment:
      # Opcional si ya usas env_file
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - ENCRYPTION_MASTER_KEY=PARALELEPIPEDO
      - KEYS_DIRECTORY=/keys/
      - OPENSSL_DIR=/etc/ssl/openssl.cnf