version: "3.8"

networks:
  chiwi_network:
    driver: bridge

volumes:
  db_users_server_data:
    driver: local
  db_chats_server_data:
    driver: local

services:
  db_users:
    image: mysql:8.0
    container_name: db_users
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_USERS}
      MYSQL_DATABASE: ${MYSQL_DATABASE_USERS}
      MYSQL_USER: ${MYSQL_USER_USERS}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_USERS}
    volumes:
      - db_users_server_data:/var/lib/mysql
    ports:
      - "${DB_USERS_PORT:-3306}:3306"  # Usa 3306 como valor por defecto si la variable no está definida
    networks:
      - chiwi_network

  db_chats:
    image: mysql:8.0
    container_name: db_chats
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_CHATS}
      MYSQL_DATABASE: ${MYSQL_DATABASE_CHATS}
      MYSQL_USER: ${MYSQL_USER_CHATS}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_CHATS}
    volumes:
      - db_chats_server_data:/var/lib/mysql
    ports:
      - "${DB_CHATS_PORT:-3307}:3306"  # Usa 3307 como valor por defecto
    networks:
      - chiwi_network

  usuarios_service:
    build: 
      context: ./usuarios_service
      dockerfile: DockerFile
    container_name: usuarios-service
    restart: unless-stopped
    volumes:
      - ./usuarios_service:/var/www/html
    environment:
      - DB_HOST=db_users
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD_USERS}
      - DB_DATABASE=${MYSQL_DATABASE_USERS}
      - DB_USERS_PORT=3306  
      - JWT_SECRET=${JWT_SECRET}
      - APP_ENV=production
      - APP_DEBUG=false
    ports:
      - "8888:80"
    depends_on:
      - db_users
    networks:
      - chiwi_network